### PR TITLE
Failure decoding compounded messages & Add no more files status

### PR DESCRIPTION
**Pull request by guybmayor**
This contains 2 different issues:

1. Failure decoding compounded messages:
I got this exception:
`2018-09-02 10:22:41.247 WARN [jcifs.smb.SmbTransportImpl] (Transport0) Failure decoding message, disconnecting transport java.io.IOException: WHAT? ( read 124 decoded 128 ): command=SMB2_CLOSE,status=0,flags=0x0005,mid=18,wordCount=0,byteCount=0 at jcifs.smb.SmbTransportImpl.doRecvSMB2(SmbTransportImpl.java:1212) at jcifs.smb.SmbTransportImpl.doRecv(SmbTransportImpl.java:1125) at jcifs.util.transport.Transport.loop(Transport.java:459) at jcifs.util.transport.Transport.run(Transport.java:762) at java.lang.Thread.run(Thread.java:748) 2018-09-02 10:23:11.242 WARN [jcifs.util.transport.Transport] (default task-14) sendrecv failed jcifs.util.transport.RequestTimeoutException: Transport0 timedout waiting for response to command=SMB2_TREE_CONNECT,status=0,flags=0x0000,mid=19,wordCount=0,byteCount=56 at jcifs.util.transport.Transport.waitForResponses(Transport.java:365) at jcifs.util.transport.Transport.sendrecv(Transport.java:232) at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1003) at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1520) at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:407) at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:345) at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:607) at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609) at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563) at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484) at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460) at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421) at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:550) at jcifs.smb.SmbFile.getType(SmbFile.java:877)`

So I start look at the SMB documentation and I found that :
https://msdn.microsoft.com/en-us/library/cc246614.aspx
> the last request of the compounded requests does not need to be padded to an 8-byte boundary. 

I also think that this is related to #80 

2. Add no more files status:
Add STATUS_NO_MORE_FILES witch is a OK answer in response for find request
https://wiki.wireshark.org/SMB2/Find

### CODE REVIEW

**Comment by mbechler** [comment]
Thanks. Yes, as noted in https://github.com/AgNO3/jcifs-ng/issues/74#issuecomment-385658812 there is no requirement for the last message in a compound chain to be padded. However, just removing the requirement is going to break the signature calculation if padding is present. 
We'll have to somehow detect whether padding is present and this is not going to be much fun unfortunately, which is the main reason I have not tackled that issue yet.

**Comment by guybmayor** [comment]
Why do you thing this will break the signature calculation if padding is present? 
it's will only padded in 8-bit if the next_command flag is on.

**Comment by mbechler** [comment]
Per spec (3.3.4.1.3):
> "the last response in the compounded responses SHOULD be padded to a multiple of 8 bytes"

so having padding is valid as well. And that padding, if present, needs to be included in the signature calculation or it won't match. Seems to me that the specification has made a pretty bad choice there.

**Comment by guybmayor** [comment]
It's really looks like there is a specification mistake here. You can also see on 3.2.5.1.9 Handling Compounded Responses:

> The final response in the compounded response chain will have NextCommand equal to 0, and it MUST be processed as an individual message of a size equal to the number of bytes remaining in this receive.

And I only post this pull request after I sow that is helped me in few environments.


Please also answer to my second issue:
2. Add no more files status:
Add STATUS_NO_MORE_FILES witch is a OK answer in response for find request
https://wiki.wireshark.org/SMB2/Find

**Comment by mbechler** [comment]
Thanks. Never noticed that sentence in the specification, that is exactly what I thought was necessary to get it working - but now confirmed. I'll look into how to pass around the remaining length.

Merging the status code addition. Have you had any issues because of this or is this cosmetic?

**Comment by guybmayor** [comment]
Actually it's a completely different issue that I set in the same pull request.

**Comment by mbechler** [comment]
What I meant was whether you have seen any actual errors without that change (e.g. an exception bubbling up to user code), or whether this was to remove the exception being logged in the debug log.

**Comment by guybmayor** [comment]
yeah of course, it's happens when the client ask for file list form the server on specific folder but all the files are already given in the previous request.

**Comment by mbechler** [comment]
Sure, but as far as I can tell that exception should haven been caught by the enumeration code, wasn't it?

**Comment by mbechler** [comment]
https://github.com/AgNO3/jcifs-ng/blob/3292a1fbc3f9fb6af928ae923b6df8e1e87882a1/src/main/java/jcifs/smb/DirFileEntryEnumIterator2.java#L145

**Comment by guybmayor** [comment]
Hi, I just review my previous pull request and I notice that you message the wrong files.
We agreed to merge the "Failure decoding compounded messages" issue and not the "Add no more files status".

Sorry confused you.

**Comment by mbechler** [comment]
I merged the "Add no more files status" just as a cosmetic measure (no more logging it as an error status). 
For the "Failure decoding compounded messages" a different approach was taken.
Or what do you mean?

**Comment by guybmayor** [comment]
Somehow I didn't notice that you take a different approach. 
That's working fine now.

**Pull request closed without merging**
