### PR TITLE
Fix handling of dfs root referrals (#78 and probably others)

### LINKED ISSUE #78: The network name cannot be found
Hi, I have the following Exception`jcifs.smb.SmbException: The network name cannot be found.
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1343)
	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1509)
	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:980)
	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1475)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397)
	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:336)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:600)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:460)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:421)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:545)
	at jcifs.smb.SmbFile.connect(SmbFile.java:504)`
when trying to connect to a DFS Share even if the searched host is available  (responds to ping and the share is visible in WindowsExplorer) .

   Another question will be if this old issue from jcifs is fixed in jcifs-ng : https://lists.samba.org/archive/jcifs/2017-May/010366.html

  Does anybody have a hint for me  ?  Thanks !

### PR DESCRIPTION
**Pull request by svella**
In a nutshell, if the DC wasn't also the namespace server, DFS lookups were failing because a) root referral requests were were incorrectly appending the path and hence actually a link request, and b) link requests were always being sent to the DC(s) instead of the result of the root referral. This fixes #78, at least as I was seeing it. It likely fixes a few of the other DNS resolution issues that were reported.

Testing this didn't require adding any tests per se - but did require an environment where the DC is not also the namespace server. In my test environment the DC, namespace server, and file server were all separate.

I do have to admit that I have not been able to get my test environment to the point where all the tests pass even before my changes were added - just don't have enough information on what the tests are expecting. But I was able to get DfsTest to pass in my environment, whereas without my changes it was failing.

### CODE REVIEW

**Comment by mbechler** [comment]
Thanks so much for looking into this. Unfortunately I did not quite get to have a closer look and do some testing today, and it might be a while till I can, but I haven't forgotten about it.

**Comment by jansohn** [comment]
Would be great if this could soon be reviewed, merged and released...

**Comment by mbechler** [comment]
Yes, really sorry for the long delay. Actually, I finally got around to start fixing my test setup last weekend, so expect this to happen some time soon.

**Comment by mbechler** [comment]
Currently running what I expect to be the final (hopefully successful) test run. Looks good to me.

My new test environments contain a domain with separate DFS namespace server as well.

Stumbled over one issue that broke a previously working setup, however after further testing and consideration determined this is a samba bug (and also does not work with windows clients): 
https://bugzilla.samba.org/show_bug.cgi?id=14305

**Pull request merged**
