### PR TITLE
NegTokenInit and DCERPC bugs

### PR DESCRIPTION
**Pull request by guybmayor**
Hi, please check my pull request.

The first issue is on NegTokenInit  context flags values (involved src/main/java/jcifs/spnego/NegTokenInit.java)

The second is on handling file servers with many (100~) shears DCERPC messages (involved src/main/java/jcifs/dcerpc/DcerpcPipeHandle.java and src/main/java/jcifs/dcerpc/DcerpcHandle.java)

### CODE REVIEW

**Comment by mbechler** [comment]
Thanks.

Can you elaborate a bit what the issue was you were experiencing and what the change in behavior is to avoid it?

So far I have understood
- fragments can be bigger than maxRecvSize (?)
- Wrong PDU header check

Isn't the doReceiveFragment now receiving multiple fragments? I think the intention of the code was that this would be handled by the other sendrecv/... code.

**Comment by guybmayor** [comment]
The problem was that I had a file server with +-100 shears, so the DCERPC answer from the server was built from 3 different DCERPC messages and each of them was built from 2-3 individual messages.

So I was needed send only one time and recive as needed fragment and in each as needed rest of the fragment

**Comment by mbechler** [comment]
Curious how that looks like. Any chance you might have a packet capture of that behavior?

PS: I'll be on vacation for a while.

**Comment by mbechler** [comment]
So, I finally had a chance to have a closer look. Sorry for the delay. 
As I had mentioned before there already was code that should have handled multiple fragments.
But it turns out that logic was badly broken. I have now committed a much simpler fix, please check whether that works for you.

**Comment by mbechler** [comment]
And now I also finally understood the other part of the patch, so this should be merged in a slightly different way, too. Thanks,again.

**Comment by guybmayor** [comment]
Hi, thanks for the response.
unfortunately, your Dcerpc changes haven't fixed the problem.

**Comment by mbechler** [comment]
Can you pinpoint further which part fails, e.g.
a) reading the complete fragment with multiple reads
b) reading following fragments
?

**Comment by guybmayor** [comment]
I have tested it again and it seems to work well now, I might have a problem last time that I have checked you fix.

Thank you.

**Pull request closed without merging**
