### PR TITLE
Added SingletonContext getInstance where we can pass in our propertie…

### PR DESCRIPTION
**Pull request by BobFleischman**
…s list

I needed this for a custom NTLM Filter that we use in our Liferay Portal.

### CODE REVIEW

**Comment by mbechler** [comment]
I think I would prefer to have that as an initalize method that fails when already initialized.

**Comment by BobFleischman** [comment]
Not sure I understand your point. I’m glad to make the change, I just need to pass in my own properties which might come from database, or even be hard coded.

If you point me in the right direction I’ll give it another try.

I am at the Spring One conference next week, so sorry if I don’t get right back to you.

Bob

**Comment by mbechler** [comment]
If you have multiple calls to getInstance(Properties), or mix with getInstance()  this will produce very different/strange results. I think it would be better to have an "initialize" method to which you can pass these custom properties and to make sure that initialization happens exactly once.

**Comment by BobFleischman** [comment]
I understand and will give this a try when I get back.

Thanks

**Comment by mbechler** [comment]
I added an init() method as I suggested. If that does not suit your needs, please open an issue.

**Comment by BobFleischman** [comment]
Thank you, will you be doing another release soon?

**Comment by mbechler** [comment]
There are still a couple of things I'd like to look into, but I guess the 2.1 release will be ready within the next couple of weeks.

**Comment by BobFleischman** [comment]
Hello:

We are anxious to use your 2.1 version. Any idea when it will be released or if we can get a snapshot version?

Building it on our PCs requires modifying Java for some security issues.

Thanks

Bob

**Comment by mbechler** [comment]
2.1 might still be a while (I'd really like to get encryption working, but I'm a bit busy right now), but the change also made it into the 2.0.4 release which is already available on maven central.

**Pull request closed without merging**
