### PR TITLE
Kerberos auto cardinals renew

### PR DESCRIPTION
**Pull request by guybmayor**

### CODE REVIEW

**Comment by mbechler** [comment]
Can you elaborate on the change at https://github.com/guybmayor/jcifs-ng/blob/88582068363f3163d412a040f822888f9592e205/src/main/java/jcifs/smb/SmbTreeConnection.java#L614 ?

My guess is that in your situtation the change makes sure that the branch is not taken. I think instead we probably should check whether the session is anonymous.

**Comment by guybmayor** [comment]
smb.SmbResourceLocatorImpl:shouldForceSigning() seems to be more general, beside checking if it's IPC it's contains checking if the session is anonymous and more related configurations.

**Comment by mbechler** [comment]
I think this code was already wrong before. I would even consider falling back from an authenticated to an anonymous session a security flaw. Imho, what we want to do is establish a new anonymous session when the original was anonymous and an authenticated one when we were authenticated.

**Comment by guybmayor** [comment]
yes, I agree with you, But isn't the pull request doing it?

**Comment by mbechler** [comment]
I think right now this will be always falling back to an anonymous session for IPC shares and never actually reauthenticating.

**Comment by mbechler** [comment]
Both I guess, the commit just made me have a closer look at that code

**Comment by guybmayor** [comment]
well the commit did solve this issue for me. I though that if shouldForceSigning equals true it have to be anonymous do there is not really anything to re-authenticating to. otherwise its need to rre-authenticating

**Comment by mbechler** [comment]
I've merged and added the commit 2c9780aa5204bc571fc0f81a2ad8fca5d1d9ebda which changes the behavior. Please check whether that still works for you.

**Comment by guybmayor** [comment]
Yes it still works. THX

**Pull request merged**
